name: TodoApp CI/CD
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensures full git history for versioning
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Restore dependencies
      run: dotnet restore --configfile NuGet.config
    
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{ steps.gitversion.outputs.semVer }}
    
    - name: Run Unit Tests
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=.
          -Dsonar.language=cs
          -Dsonar.scanner.scanAll=false
          -Dsonar.exclusions=**/obj/**,**/bin/**
          -Dsonar.coverage.exclusions=**/Program.cs,**/Startup.cs
          -Dsonar.branch.name=${{ github.ref_name }}
    
    - name: Set up Docker Buildx
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/abbanks/todoapp-api:latest
          ghcr.io/abbanks/todoapp-api:${{ steps.gitversion.outputs.semVer }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}
        generate_release_notes: true